# Generated by Django 4.0.6 on 2022-08-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_post_likes_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above to View Blog Content...', max_length=255),
        ),
    ]
