# Generated by Django 4.0.6 on 2022-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
