# Generated by Django 4.0.6 on 2022-08-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_post_post_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_updated',
            new_name='updated_date',
        ),
    ]
