# Generated by Django 4.0.6 on 2022-07-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type', models.CharField(help_text='Enter your language of the book you want(e.g English, Farsi)', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.ManyToManyField(help_text='Select your language for this book', to='catalog.language'),
        ),
    ]
